#!/usr/bin/env bash
aws dynamodb create-table --cli-input-json file://../db/create-table-watches.json --region eu-west-3
aws dynamodb batch-write-item --request-items file://../db/adapted_watches_0.json
aws dynamodb batch-write-item --request-items file://../db/adapted_watches_1.json
aws dynamodb batch-write-item --request-items file://../db/adapted_watches_2.json
aws dynamodb batch-write-item --request-items file://../db/adapted_watches_3.json
aws dynamodb batch-write-item --request-items file://../db/adapted_watches_4.json
aws dynamodb batch-write-item --request-items file://../db/adapted_watches_5.json
aws dynamodb batch-write-item --request-items file://../db/adapted_watches_6.json
aws dynamodb batch-write-item --request-items file://../db/adapted_watches_7.json
aws dynamodb batch-write-item --request-items file://../db/adapted_watches_8.json
aws dynamodb batch-write-item --request-items file://../db/adapted_watches_9.json
aws dynamodb batch-write-item --request-items file://../db/adapted_watches_10.json
aws dynamodb batch-write-item --request-items file://../db/adapted_watches_11.json
aws dynamodb batch-write-item --request-items file://../db/adapted_watches_12.json
aws dynamodb batch-write-item --request-items file://../db/adapted_watches_13.json
aws dynamodb batch-write-item --request-items file://../db/adapted_watches_14.json
aws dynamodb batch-write-item --request-items file://../db/adapted_watches_15.json
aws dynamodb batch-write-item --request-items file://../db/adapted_watches_16.json
aws dynamodb batch-write-item --request-items file://../db/adapted_watches_17.json
aws dynamodb batch-write-item --request-items file://../db/adapted_watches_18.json
aws dynamodb batch-write-item --request-items file://../db/adapted_watches_19.json
aws dynamodb batch-write-item --request-items file://../db/adapted_watches_20.json
aws dynamodb batch-write-item --request-items file://../db/adapted_watches_21.json
aws dynamodb batch-write-item --request-items file://../db/adapted_watches_22.json
aws dynamodb batch-write-item --request-items file://../db/adapted_watches_23.json
aws dynamodb batch-write-item --request-items file://../db/adapted_watches_24.json
aws dynamodb batch-write-item --request-items file://../db/adapted_watches_25.json
aws dynamodb batch-write-item --request-items file://../db/adapted_watches_26.json
aws dynamodb batch-write-item --request-items file://../db/adapted_watches_27.json
aws dynamodb batch-write-item --request-items file://../db/adapted_watches_28.json
aws dynamodb batch-write-item --request-items file://../db/adapted_watches_29.json
aws dynamodb batch-write-item --request-items file://../db/adapted_watches_30.json
aws dynamodb batch-write-item --request-items file://../db/adapted_watches_31.json
aws dynamodb batch-write-item --request-items file://../db/adapted_watches_32.json
aws dynamodb batch-write-item --request-items file://../db/adapted_watches_33.json
aws dynamodb batch-write-item --request-items file://../db/adapted_watches_34.json
aws dynamodb batch-write-item --request-items file://../db/adapted_watches_35.json
aws dynamodb batch-write-item --request-items file://../db/adapted_watches_36.json
aws dynamodb batch-write-item --request-items file://../db/adapted_watches_37.json
aws dynamodb batch-write-item --request-items file://../db/adapted_watches_38.json
aws dynamodb batch-write-item --request-items file://../db/adapted_watches_39.json
aws dynamodb batch-write-item --request-items file://../db/adapted_watches_40.json
aws dynamodb batch-write-item --request-items file://../db/adapted_watches_41.json
aws dynamodb batch-write-item --request-items file://../db/adapted_watches_42.json
aws dynamodb batch-write-item --request-items file://../db/adapted_watches_43.json
aws dynamodb batch-write-item --request-items file://../db/adapted_watches_44.json
aws dynamodb batch-write-item --request-items file://../db/adapted_watches_45.json
aws dynamodb batch-write-item --request-items file://../db/adapted_watches_46.json
aws dynamodb batch-write-item --request-items file://../db/adapted_watches_47.json
aws dynamodb batch-write-item --request-items file://../db/adapted_watches_48.json
aws dynamodb batch-write-item --request-items file://../db/adapted_watches_49.json
aws dynamodb batch-write-item --request-items file://../db/adapted_watches_50.json
aws dynamodb batch-write-item --request-items file://../db/adapted_watches_51.json
aws dynamodb batch-write-item --request-items file://../db/adapted_watches_52.json
aws dynamodb batch-write-item --request-items file://../db/adapted_watches_53.json
aws dynamodb batch-write-item --request-items file://../db/adapted_watches_54.json
aws dynamodb batch-write-item --request-items file://../db/adapted_watches_55.json
aws dynamodb batch-write-item --request-items file://../db/adapted_watches_56.json
aws dynamodb batch-write-item --request-items file://../db/adapted_watches_57.json
aws dynamodb batch-write-item --request-items file://../db/adapted_watches_58.json
aws dynamodb batch-write-item --request-items file://../db/adapted_watches_59.json
aws dynamodb batch-write-item --request-items file://../db/adapted_watches_60.json
aws dynamodb batch-write-item --request-items file://../db/adapted_watches_61.json
aws dynamodb batch-write-item --request-items file://../db/adapted_watches_62.json
aws dynamodb batch-write-item --request-items file://../db/adapted_watches_63.json
aws dynamodb batch-write-item --request-items file://../db/adapted_watches_64.json
aws dynamodb batch-write-item --request-items file://../db/adapted_watches_65.json
aws dynamodb batch-write-item --request-items file://../db/adapted_watches_66.json
aws dynamodb batch-write-item --request-items file://../db/adapted_watches_67.json
aws dynamodb batch-write-item --request-items file://../db/adapted_watches_68.json
aws dynamodb batch-write-item --request-items file://../db/adapted_watches_69.json
aws dynamodb batch-write-item --request-items file://../db/adapted_watches_70.json
aws dynamodb batch-write-item --request-items file://../db/adapted_watches_71.json
aws dynamodb batch-write-item --request-items file://../db/adapted_watches_72.json
aws dynamodb batch-write-item --request-items file://../db/adapted_watches_73.json
aws dynamodb batch-write-item --request-items file://../db/adapted_watches_74.json
aws dynamodb batch-write-item --request-items file://../db/adapted_watches_75.json
aws dynamodb batch-write-item --request-items file://../db/adapted_watches_76.json
aws dynamodb batch-write-item --request-items file://../db/adapted_watches_77.json
aws dynamodb batch-write-item --request-items file://../db/adapted_watches_78.json
aws dynamodb batch-write-item --request-items file://../db/adapted_watches_79.json
aws dynamodb batch-write-item --request-items file://../db/adapted_watches_80.json
aws dynamodb batch-write-item --request-items file://../db/adapted_watches_81.json
aws dynamodb batch-write-item --request-items file://../db/adapted_watches_82.json
aws dynamodb batch-write-item --request-items file://../db/adapted_watches_83.json
aws dynamodb batch-write-item --request-items file://../db/adapted_watches_84.json
aws dynamodb batch-write-item --request-items file://../db/adapted_watches_85.json
aws dynamodb batch-write-item --request-items file://../db/adapted_watches_86.json
aws dynamodb batch-write-item --request-items file://../db/adapted_watches_87.json
aws dynamodb batch-write-item --request-items file://../db/adapted_watches_88.json
aws dynamodb batch-write-item --request-items file://../db/adapted_watches_89.json
aws dynamodb batch-write-item --request-items file://../db/adapted_watches_90.json
aws dynamodb batch-write-item --request-items file://../db/adapted_watches_91.json
aws dynamodb batch-write-item --request-items file://../db/adapted_watches_92.json
aws dynamodb batch-write-item --request-items file://../db/adapted_watches_93.json
aws dynamodb batch-write-item --request-items file://../db/adapted_watches_94.json
aws dynamodb batch-write-item --request-items file://../db/adapted_watches_95.json
aws dynamodb batch-write-item --request-items file://../db/adapted_watches_96.json
aws dynamodb batch-write-item --request-items file://../db/adapted_watches_97.json
aws dynamodb batch-write-item --request-items file://../db/adapted_watches_98.json
aws dynamodb batch-write-item --request-items file://../db/adapted_watches_99.json
aws dynamodb batch-write-item --request-items file://../db/adapted_watches_100.json
aws dynamodb batch-write-item --request-items file://../db/adapted_watches_101.json
aws dynamodb batch-write-item --request-items file://../db/adapted_watches_102.json
aws dynamodb batch-write-item --request-items file://../db/adapted_watches_103.json
aws dynamodb batch-write-item --request-items file://../db/adapted_watches_104.json
aws dynamodb batch-write-item --request-items file://../db/adapted_watches_105.json
aws dynamodb batch-write-item --request-items file://../db/adapted_watches_106.json
aws dynamodb batch-write-item --request-items file://../db/adapted_watches_107.json
aws dynamodb batch-write-item --request-items file://../db/adapted_watches_108.json
aws dynamodb batch-write-item --request-items file://../db/adapted_watches_109.json
aws dynamodb batch-write-item --request-items file://../db/adapted_watches_110.json
aws dynamodb batch-write-item --request-items file://../db/adapted_watches_111.json
aws dynamodb batch-write-item --request-items file://../db/adapted_watches_112.json
aws dynamodb batch-write-item --request-items file://../db/adapted_watches_113.json
aws dynamodb batch-write-item --request-items file://../db/adapted_watches_114.json
aws dynamodb batch-write-item --request-items file://../db/adapted_watches_115.json
aws dynamodb batch-write-item --request-items file://../db/adapted_watches_116.json
aws dynamodb batch-write-item --request-items file://../db/adapted_watches_117.json
aws dynamodb batch-write-item --request-items file://../db/adapted_watches_118.json
aws dynamodb batch-write-item --request-items file://../db/adapted_watches_119.json
aws dynamodb batch-write-item --request-items file://../db/adapted_watches_120.json
aws dynamodb batch-write-item --request-items file://../db/adapted_watches_121.json
aws dynamodb batch-write-item --request-items file://../db/adapted_watches_122.json
aws dynamodb batch-write-item --request-items file://../db/adapted_watches_123.json
aws dynamodb batch-write-item --request-items file://../db/adapted_watches_124.json
aws dynamodb batch-write-item --request-items file://../db/adapted_watches_125.json
aws dynamodb batch-write-item --request-items file://../db/adapted_watches_126.json
aws dynamodb batch-write-item --request-items file://../db/adapted_watches_127.json
aws dynamodb batch-write-item --request-items file://../db/adapted_watches_128.json
aws dynamodb batch-write-item --request-items file://../db/adapted_watches_129.json
aws dynamodb batch-write-item --request-items file://../db/adapted_watches_130.json
aws dynamodb batch-write-item --request-items file://../db/adapted_watches_131.json
aws dynamodb batch-write-item --request-items file://../db/adapted_watches_132.json
aws dynamodb batch-write-item --request-items file://../db/adapted_watches_133.json
aws dynamodb batch-write-item --request-items file://../db/adapted_watches_134.json
aws dynamodb batch-write-item --request-items file://../db/adapted_watches_135.json
aws dynamodb batch-write-item --request-items file://../db/adapted_watches_136.json
aws dynamodb batch-write-item --request-items file://../db/adapted_watches_137.json
aws dynamodb batch-write-item --request-items file://../db/adapted_watches_138.json
aws dynamodb batch-write-item --request-items file://../db/adapted_watches_139.json
aws dynamodb batch-write-item --request-items file://../db/adapted_watches_140.json
aws dynamodb batch-write-item --request-items file://../db/adapted_watches_141.json
aws dynamodb batch-write-item --request-items file://../db/adapted_watches_142.json
aws dynamodb batch-write-item --request-items file://../db/adapted_watches_143.json
aws dynamodb batch-write-item --request-items file://../db/adapted_watches_144.json
aws dynamodb batch-write-item --request-items file://../db/adapted_watches_145.json
aws dynamodb batch-write-item --request-items file://../db/adapted_watches_146.json
aws dynamodb batch-write-item --request-items file://../db/adapted_watches_147.json
aws dynamodb batch-write-item --request-items file://../db/adapted_watches_148.json
aws dynamodb batch-write-item --request-items file://../db/adapted_watches_149.json
aws dynamodb batch-write-item --request-items file://../db/adapted_watches_150.json
aws dynamodb batch-write-item --request-items file://../db/adapted_watches_151.json
aws dynamodb batch-write-item --request-items file://../db/adapted_watches_152.json
aws dynamodb batch-write-item --request-items file://../db/adapted_watches_153.json
aws dynamodb batch-write-item --request-items file://../db/adapted_watches_154.json
aws dynamodb batch-write-item --request-items file://../db/adapted_watches_155.json
aws dynamodb batch-write-item --request-items file://../db/adapted_watches_156.json
aws dynamodb batch-write-item --request-items file://../db/adapted_watches_157.json
aws dynamodb batch-write-item --request-items file://../db/adapted_watches_158.json
aws dynamodb batch-write-item --request-items file://../db/adapted_watches_159.json
aws dynamodb batch-write-item --request-items file://../db/adapted_watches_160.json
aws dynamodb batch-write-item --request-items file://../db/adapted_watches_161.json
aws dynamodb batch-write-item --request-items file://../db/adapted_watches_162.json
aws dynamodb batch-write-item --request-items file://../db/adapted_watches_163.json
aws dynamodb batch-write-item --request-items file://../db/adapted_watches_164.json
aws dynamodb batch-write-item --request-items file://../db/adapted_watches_165.json
