version: '3'
services:
  db:
    image: mysql/mysql-server:5.7
    environment:
      - MYSQL_USER=watches
      - MYSQL_PASSWORD=watches
      - MYSQL_ROOT_PASSWORD=watches
      - MYSQL_DATABASE=watches
    volumes:
      - ./db:/docker-entrypoint-initdb.d
    restart: always
    ports:
      - 33006:3306
    
  info-service-v2:
    build: ./python_server
    ports:
      - 1080:1080
    depends_on:
      - db
    environment:
      - FLASK_APP=server.py
      - DB_HOST=db #db is an alias for the ip address of the mysql container
      - DB_PORT=3306
      - DB_DBNAME=watches
      - DB_USER=watches
      - DB_PASS=watches
      - HTTP_USER=cloud
      - HTTP_PASS=computing
    restart: always